services:
  postgres:
    image: postgres:16
    container_name: rdm-postgres
    environment:
      POSTGRES_USER: rdm
      POSTGRES_PASSWORD: rdm
      POSTGRES_DB: rdmdb
    ports:
      - "5433:5432"
    volumes:
      - rdm_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rdm -d rdmdb"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rdm-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=rdmdb;Username=rdm;Password=rdm"
      S3__Endpoint: "10.225.211.40:80"
      S3__AccessKey: "8JOU3IXU0PBENO571FUD"
      S3__SecretKey: "wyfVKXNNt4SxM21jqTVLxvxYlGyzssEGibcUP4U4"
      S3__Bucket: "final"
      S3__UseSsl: "false"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  rdm_pgdata:

