// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RdmApi.Data;

#nullable disable

namespace RdmApi.Migrations
{
    [DbContext(typeof(RdmDbContext))]
    [Migration("20260328111210_AddDatasetVersionFiles")]
    partial class AddDatasetVersionFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RdmApi.Data.Entities.Annotation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DatasetVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.HasIndex("DatasetVersionId");

                    b.ToTable("Annotations");
                });

            modelBuilder.Entity("RdmApi.Data.Entities.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<string>("DetailJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("RdmApi.Data.Entities.Dataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("RdmApi.Data.Entities.DatasetRelationship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SourceDatasetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetDatasetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceDatasetId");

                    b.HasIndex("TargetDatasetId");

                    b.ToTable("DatasetRelationships");
                });

            modelBuilder.Entity("RdmApi.Data.Entities.DatasetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeDescription")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("DatasetVersions");
                });

            modelBuilder.Entity("RdmApi.Data.Entities.DatasetVersionFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHashSha256")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DatasetVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelativePath")
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DatasetVersionId");

                    b.ToTable("DatasetVersionFiles");
                });

            modelBuilder.Entity("RdmApi.Data.Entities.Annotation", b =>
                {
                    b.HasOne("RdmApi.Data.Entities.Dataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RdmApi.Data.Entities.DatasetVersion", "DatasetVersion")
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Dataset");

                    b.Navigation("DatasetVersion");
                });

            modelBuilder.Entity("RdmApi.Data.Entities.DatasetRelationship", b =>
                {
                    b.HasOne("RdmApi.Data.Entities.Dataset", "SourceDataset")
                        .WithMany()
                        .HasForeignKey("SourceDatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RdmApi.Data.Entities.Dataset", "TargetDataset")
                        .WithMany()
                        .HasForeignKey("TargetDatasetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceDataset");

                    b.Navigation("TargetDataset");
                });

            modelBuilder.Entity("RdmApi.Data.Entities.DatasetVersion", b =>
                {
                    b.HasOne("RdmApi.Data.Entities.Dataset", "Dataset")
                        .WithMany("Versions")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("RdmApi.Data.Entities.DatasetVersionFile", b =>
                {
                    b.HasOne("RdmApi.Data.Entities.DatasetVersion", "DatasetVersion")
                        .WithMany("Files")
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatasetVersion");
                });

            modelBuilder.Entity("RdmApi.Data.Entities.Dataset", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("RdmApi.Data.Entities.DatasetVersion", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
