CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AuditEvents" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Timestamp" timestamp with time zone NOT NULL,
    "Actor" character varying(200) NOT NULL,
    "Action" character varying(100) NOT NULL,
    "DatasetId" uuid,
    "DetailJson" text,
    CONSTRAINT "PK_AuditEvents" PRIMARY KEY ("Id")
);

CREATE TABLE "Datasets" (
    "Id" uuid NOT NULL,
    "Title" character varying(300) NOT NULL,
    "Description" text,
    "Creator" character varying(200) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Datasets" PRIMARY KEY ("Id")
);

CREATE TABLE "DatasetVersions" (
    "Id" uuid NOT NULL,
    "DatasetId" uuid NOT NULL,
    "VersionNumber" integer NOT NULL,
    "StorageKey" text,
    "ContentHashSha256" text,
    "SizeBytes" bigint,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DatasetVersions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DatasetVersions_Datasets_DatasetId" FOREIGN KEY ("DatasetId") REFERENCES "Datasets" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_DatasetVersions_DatasetId_VersionNumber" ON "DatasetVersions" ("DatasetId", "VersionNumber");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260208194201_InitialCreate', '8.0.2');

COMMIT;

START TRANSACTION;

CREATE TABLE "Annotations" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Actor" character varying(200) NOT NULL,
    "DatasetId" uuid NOT NULL,
    "DatasetVersionId" uuid,
    "Text" character varying(4000) NOT NULL,
    CONSTRAINT "PK_Annotations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Annotations_DatasetVersions_DatasetVersionId" FOREIGN KEY ("DatasetVersionId") REFERENCES "DatasetVersions" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Annotations_Datasets_DatasetId" FOREIGN KEY ("DatasetId") REFERENCES "Datasets" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Annotations_DatasetId" ON "Annotations" ("DatasetId");

CREATE INDEX "IX_Annotations_DatasetVersionId" ON "Annotations" ("DatasetVersionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260223151406_AddAnnotations', '8.0.2');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260228154323_AddDatasetStatusAndTags', '8.0.2');

COMMIT;

START TRANSACTION;

ALTER TABLE "DatasetVersions" ADD "ChangeDescription" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260308205351_AddChangeDescriptionToDatasetVersion', '8.0.2');

COMMIT;

START TRANSACTION;

CREATE TABLE "DatasetRelationships" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "SourceDatasetId" uuid NOT NULL,
    "TargetDatasetId" uuid NOT NULL,
    "RelationType" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DatasetRelationships" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DatasetRelationships_Datasets_SourceDatasetId" FOREIGN KEY ("SourceDatasetId") REFERENCES "Datasets" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DatasetRelationships_Datasets_TargetDatasetId" FOREIGN KEY ("TargetDatasetId") REFERENCES "Datasets" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_DatasetRelationships_SourceDatasetId" ON "DatasetRelationships" ("SourceDatasetId");

CREATE INDEX "IX_DatasetRelationships_TargetDatasetId" ON "DatasetRelationships" ("TargetDatasetId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260309102040_AddDatasetRelationships', '8.0.2');

COMMIT;

